# Generated by Django 2.0 on 2020-01-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('index', models.CharField(default='', max_length=32, verbose_name='题号')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='题目')),
                ('options', jsonfield.fields.JSONField(max_length=1000, verbose_name='选项内容')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('creator', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(default='', max_length=64, verbose_name='科目名称')),
                ('chapter', models.CharField(default='', max_length=32, verbose_name='章节号')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='总结内容')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='miscollection.Summary', verbose_name='上一目录')),
            ],
            options={
                'verbose_name': '总结',
                'verbose_name_plural': '总结',
            },
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
