# Generated by Django 2.0 on 2020-01-02 11:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miscollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='miscollection.Summary', verbose_name='上一目录'),
        ),
    ]
