# -*- coding: utf-8 -*-
# 常规字段长度定义
LEN_SHORT = 32
LEN_NORMAL = 64
LEN_MIDDLE = 128
LEN_DESC = 500
LEN_LONG = 255
LEN_X_LONG = 1000
LEN_XX_LONG = 10000
LEN_XXX_LONG = 20000

# 字段默认值
EMPTY_INT = 0
EMPTY_STRING = ""
EMPTY_LIST = []
EMPTY_DICT = {}
DEFAULT_BK_BIZ_ID = -1

# 公共常量定义
DEFAULT_STRING = "DEFAULT"
DEFAULT_VERSION = "0"

FRONT_ORDER = 0
END_ORDER = 9999
DEFAULT_ORDER = -1
NO_LIMIT = 0